development:
  rpc_host: localhost
  rpc_port: 8101
  rpc_whitelist: "*"
  minerthreads: 1
  genesis_block: config/genesis/dev_genesis.json
  datadir: /tmp/embark
  chains: config/chains/development.json
  mine_when_needed: true
  console: false
  account:
    init: true
    password: config/password
  ConfigInterface:
    gas_limit: 5000000
  Config:
    gas_limit: 1000000
  Proposal:
    gas_limit: 1000000
    args:
      - $Config
      - 0x0947E734fEf9B766a846633B716fF25472dC9b5A
      - 0xE3c9296D9ADE225045cFb1Dd7aBFa426a4A58fCb
      - "testnet"
      - true
  Token:
    args:
      - $Config
  TokenSales:
    args:
      - $Config
  gas_limit: 500000
  gas_price: 10000000000000
staging:
  testnet: true
  rpc_host: localhost
  rpc_port: 8101
  rpc_whitelist: "*"
  datadir: default
  network_id: 0
  deploy_timeout: 45
  console: true
  account:
    init: false
    address:
production:
  rpc_host: localhost
  rpc_port: 8101
  rpc_whitelist: "*"
  datadir: default
  network_id: 1
  console: true
  account:
    init: false
    address:
